In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier

In [2]:
data = {
    "Ad Budget ($1000s)": [1.1, 2.3, 3.0, 4.1, 5.0, 6.2, 7.1, 8.5, 9.0, 10.1],
    "Social Media Spend ($1000s)": [0.5, 1.2, 1.8, 2.5, 3.0, 3.8, 4.5, 5.0, 5.8, 6.5],
    "TV Ads ($1000s)": [2.0, 3.5, 4.2, 5.0, 5.8, 6.5, 7.2, 8.0, 8.8, 9.5],
    "Sales ($1000s)": [10.2, 20.3, 25.4, 35.1, 40.5, 50.3, 55.6, 70.2, 75.8, 85.0],
    "Sales Category": ["Low", "Medium", "Medium", "High", "High", "High", "Very High", "Very High", "Very High", "Very High"]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

Ad Budget ($1000s)  Social Media Spend ($1000s)  TV Ads ($1000s)  \
0                 1.1                          0.5              2.0   
1                 2.3                          1.2              3.5   
2                 3.0                          1.8              4.2   
3                 4.1                          2.5              5.0   
4                 5.0                          3.0              5.8   
5                 6.2                          3.8              6.5   
6                 7.1                          4.5              7.2   
7                 8.5                          5.0              8.0   
8                 9.0                          5.8              8.8   
9                10.1                          6.5              9.5   

   Sales ($1000s) Sales Category  
0            10.2            Low  
1            20.3         Medium  
2            25.4         Medium  
3            35.1           High  
4            40.5           High  
5            50.3           High  
6            55.6      Very High  
7            70.2      Very High  
8            75.8      Very High  
9            85.0      Very High

In [5]:
X = df[['Ad Budget ($1000s)','Social Media Spend ($1000s)','TV Ads ($1000s)']]
y = df['Sales ($1000s)']

x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 1)
x_train,y_train

(   Ad Budget ($1000s)  Social Media Spend ($1000s)  TV Ads ($1000s)
 6                 7.1                          4.5              7.2
 4                 5.0                          3.0              5.8
 0                 1.1                          0.5              2.0
 3                 4.1                          2.5              5.0
 1                 2.3                          1.2              3.5
 7                 8.5                          5.0              8.0
 8                 9.0                          5.8              8.8
 5                 6.2                          3.8              6.5,
 6    55.6
 4    40.5
 0    10.2
 3    35.1
 1    20.3
 7    70.2
 8    75.8
 5    50.3
 Name: Sales ($1000s), dtype: float64)

In [6]:
lin_reg = LinearRegression()
lin_reg.fit(x_train, y_train)

LinearRegression()

In [7]:
y_test

2    25.4
9    85.0
Name: Sales ($1000s), dtype: float64

In [8]:
lin_reg.predict(x_test)

array([25.21723752, 82.5357937 ])

In [9]:
new_X = np.array([[12.0,6.0,2.0], [15.0,12.0,4.0]])
lin_reg.predict(new_X)

C:\Users\HP\anaconda5\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([ 99.82848253, 122.90327309])

In [10]:
new_X1 = np.array(X)
df['lin_reg'] = lin_reg.predict(new_X1)

C:\Users\HP\anaconda5\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [11]:
def Sales(Amount):
    if Amount >= 25:
        return 1
    else:
        return 0

df['Salesabove25'] = df['Sales ($1000s)'].apply(Sales)
df

Ad Budget ($1000s)  Social Media Spend ($1000s)  TV Ads ($1000s)  \
0                 1.1                          0.5              2.0   
1                 2.3                          1.2              3.5   
2                 3.0                          1.8              4.2   
3                 4.1                          2.5              5.0   
4                 5.0                          3.0              5.8   
5                 6.2                          3.8              6.5   
6                 7.1                          4.5              7.2   
7                 8.5                          5.0              8.0   
8                 9.0                          5.8              8.8   
9                10.1                          6.5              9.5   

   Sales ($1000s) Sales Category    lin_reg  Salesabove25  
0            10.2            Low  10.016781             0  
1            20.3         Medium  19.634945             0  
2            25.4         Medium  25.217238             1  
3            35.1           High  34.109280             1  
4            40.5           High  41.382598             1  
5            50.3           High  51.100103             1  
6            55.6      Very High  58.330587             1  
7            70.2      Very High  69.798055             1  
8            75.8      Very High  73.627650             1  
9            85.0      Very High  82.535794             1

In [12]:
y1 = df['Salesabove25']

x1_train, x1_test, y1_train, y1_test = train_test_split(X, y1, test_size = 0.2, random_state=1)

logmodel = LogisticRegression()
logmodel.fit(x1_train.round(0),y1_train)

LogisticRegression()

In [13]:
logmodel.predict(x_test)

array([1, 1], dtype=int64)

In [14]:
new_X2 = np.array(X)
df['log_reg'] = logmodel.predict(new_X2)

C:\Users\HP\anaconda5\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [15]:
new_X3 = np.array([[2.5,1.0,1.5], [15.0,8.0,2.5]])
logmodel.predict(new_X3)

C:\Users\HP\anaconda5\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0, 1], dtype=int64)

In [16]:
df

Ad Budget ($1000s)  Social Media Spend ($1000s)  TV Ads ($1000s)  \
0                 1.1                          0.5              2.0   
1                 2.3                          1.2              3.5   
2                 3.0                          1.8              4.2   
3                 4.1                          2.5              5.0   
4                 5.0                          3.0              5.8   
5                 6.2                          3.8              6.5   
6                 7.1                          4.5              7.2   
7                 8.5                          5.0              8.0   
8                 9.0                          5.8              8.8   
9                10.1                          6.5              9.5   

   Sales ($1000s) Sales Category    lin_reg  Salesabove25  log_reg  
0            10.2            Low  10.016781             0        0  
1            20.3         Medium  19.634945             0        0  
2            25.4         Medium  25.217238             1        1  
3            35.1           High  34.109280             1        1  
4            40.5           High  41.382598             1        1  
5            50.3           High  51.100103             1        1  
6            55.6      Very High  58.330587             1        1  
7            70.2      Very High  69.798055             1        1  
8            75.8      Very High  73.627650             1        1  
9            85.0      Very High  82.535794             1        1

In [17]:
kmeans = KMeans(n_clusters=4)
kmeans.fit(df.drop('Sales Category',axis=1))

C:\Users\HP\anaconda5\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=4)

In [20]:
clusters = kmeans.labels_
df['Kmeans'] = clusters

In [36]:
kmeans.predict([[12,4,6,5,7,8,4]])

C:\Users\HP\anaconda5\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


array([2])

In [38]:
knn = KNeighborsClassifier(n_neighbors = 5)

In [40]:
x2 = df[['Ad Budget ($1000s)','Sales ($1000s)']]
y2 = df['Sales Category']

x2_train, x2_test, y2_train, y2_test = train_test_split(x2,y2,test_size=0.2,random_state=2)

knn.fit(x2_train,y2_train)

KNeighborsClassifier()

In [42]:
knn.predict([[160,12]])

C:\Users\HP\anaconda5\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['High'], dtype=object)